from __future__ import annotations


def encrypt_payload_aes_256_cbc(payload: bytes, key: bytes, iv: bytes) -> bytes:
    """Encrypt payload bytes with AES-256-CBC before embedding.

    Proposal alignment:
    - Reference specification: ``docs/proposals/proposal_updated_3.tex``,
      Sections ``Chosen Approaches -> Encryption`` and
      ``Experiments -> Exp. 5 (RQ5)``.

    Intended implementation:
    - Validate ``key`` length == 32 bytes and ``iv`` length == 16 bytes.
    - Apply standard AES-256 in CBC mode with PKCS#7-style padding so the
      ciphertext length is block aligned.
    - Keep the implementation deterministic for a fixed ``payload``, ``key``,
      and ``iv``. The runner already fixes IV generation per group and payload
      level for reproducible experiments.
    - Return ciphertext bytes only. Disk I/O stays in the runner.

    Inputs:
    - ``payload``: pseudo-random plaintext bitstream generated by the pipeline.
    - ``key``: 32-byte AES key.
    - ``iv``: 16-byte CBC IV.

    Output:
    - Ciphertext bytes ready for embedding.

    Reference to follow for implementation:
    - Standard AES-256-CBC cryptographic library semantics. The proposal does
      not introduce a custom cryptographic variant.
    """
    raise NotImplementedError("AES-256-CBC encryption is not implemented yet.")


def decrypt_payload_aes_256_cbc(ciphertext: bytes, key: bytes, iv: bytes) -> bytes:
    """Decrypt AES-256-CBC ciphertext back to the original payload bytes.

    This function exists mainly for validation and round-trip testing of the
    proposal's encrypted branch. It should mirror
    ``encrypt_payload_aes_256_cbc`` exactly, including key/IV validation and
    padding removal.
    """
    raise NotImplementedError("AES-256-CBC decryption is not implemented yet.")
